### ISSUE TITLE
No module named 'pkg_resources.py2_warn'

### ISSUE THREAD

**Issue by brunowego** [nutellinoit/kubenvz#12]
Hi! Currently the last version not are working. I did the installation using homebrew. I'm using macOS Big Sur. Thanks.

```sh
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/pkg_resources/__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[72814] Failed to execute script pyi_rth_pkgres
```

**Comment by yudar1024** [comment]
same problem here

**Comment by nutellinoit** [comment]
Hi guys, thanks for reporting the problem, i upgraded to big sur too and i got the same error.
I hope to fix the problem this month
